extends:
  - semantic-release-preconfigured-conventional-commits
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  -
    - "@semantic-release/exec"
    - publishCmd: |
        IMAGE_NAME="danysk/docker-manjaro-texlive-ruby"
        docker build -t "$IMAGE_NAME:${nextRelease.version}"
        docker push --all-tags "$IMAGE_NAME"
  - "@semantic-release/github"
  - "@semantic-release/git"
